name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testing.yml

  deploy:
    needs: test
    name: Deploy with Docker Compose
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy .env.production File
      run: |
        echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
      env:
        ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}

    - name: Stop Preexisting Containers
      run: |
        docker compose --profile production --env-file .env.production down || true

    - name: Build Docker Images
      run: |
        docker compose --profile production --env-file .env.production build --no-cache

    - name: Deploy Application
      run: |
        docker compose --profile production --env-file .env.production up -d
