name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feat/*
  pull_request:
    branches:
      - main
      - dev
      - feat/*
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci-reusable.yml
