name: CI Pipeline

on:
  push:
    branches:
      - dev
      - feat/*
  pull_request:
    branches:
      - dev
      - feat/*
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testing.yml
